name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.10.0
      with:
        gradle-version: wrapper
        dependency-graph: generate-and-submit
    - name: Run tests
      run: |
        ./gradlew test
    - name: Publish Test Results
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: "**/TEST-*.xml"
